### ISSUE TITLE
Add open source license for PolygonAreaCalculator

### ISSUE THREAD

**Issue by yungyuc** [Kang-Ding-Xin-NYCU/PolygonAreaCaculator#1]
@Kang-Ding-Xin-NYCU , please add an open source license for your project. If you are not sure how to do it, see https://github.com/solvcon/modmesh.

**Comment by yungyuc** [comment]
@Kang-Ding-Xin-NYCU , I saw you added the license with ab3204c47ef33572741b03aec3f283d2a2170a39.

Don't forget to update the issue once you address it.

**Comment by Kang-Ding-Xin-NYCU** [comment]
OK, I will do it next time.
